fix: update dependabot workflow to use new metadata fetching method

diff --git a/.github/workflows/pull_request_dependabot.yml b/.github/workflows/pull_request_dependabot.yml
--- a/.github/workflows/pull_request_dependabot.yml
+++ b/.github/workflows/pull_request_dependabot.yml
@@ -18,45 +18,17 @@ jobs:
     name: 'Dependabot Check'
     runs-on: ubuntu-latest
     outputs:
-      nx-version: ${{ steps.check-nx-versions.outputs.nx-version }}
-      dependency-names: ${{ steps.check-nx-versions.outputs.dependency-names }}
+      dependency-names: ${{ steps.metadata.outputs.dependency-names }}
+      update-type: ${{ steps.metadata.outputs.update-type }}
+      dependency-versions: ${{ steps.metadata.outputs.new-version }}
     if: ${{ github.event.pull_request.user.login == 'dependabot[bot]'}}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Fetch pull request details
-        id: fetch-pr-details
-        uses: actions/github-script@v7
+      - name: Fetch dependabot metadata
+        id: metadata
+        uses: dependabot/fetch-metadata@v2.2.0
         with:
-          script: |
-            const pr = await github.pulls.get({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              pull_number: context.issue.number,
-            });
-            return pr.data.body;
-
-      - name: Check for singular version for all @nx/ packages
-        id: check-nx-versions
-        run: |
-          echo "${{ steps.fetch-pr-details.outputs.result }}" > pr_description.txt
-          NX_VERSIONS=$(grep -oP '@nx/[^:]+: \K[^,]+' pr_description.txt | sort | uniq)
-          if [ $(echo "$NX_VERSIONS" | wc -l) -ne 1; then
-            echo "Error: Multiple versions found for @nx/ packages: $NX_VERSIONS"
-            exit 1
-          fi
-          NX_VERSION=$(echo "$NX_VERSIONS" | head -n 1)
-          echo "nx-version=$NX_VERSION" >> $GITHUB_ENV
-          echo "::set-output name=nx-version::$NX_VERSION"
-
-          DEPENDENCY_NAMES=$(grep -oP '@nx/[^:]+(?=:)' pr_description.txt | sort | uniq | tr '\n' ' ')
-          echo "dependency-names=$DEPENDENCY_NAMES" >> $GITHUB_ENV
-          echo "::set-output name=dependency-names::$DEPENDENCY_NAMES"
-
-      - name: Output new versions
-        run: |
-          echo "New versions: ${{ steps.fetch-pr-details.outputs.result }}"
+          github-token: '${{ secrets.GITHUB_TOKEN }}'
+          skip-commit-verification: true
 
   nx-migrate:
     name: 'NX Migrate'
@@ -81,7 +53,7 @@ jobs:
       - name: 'Get nx version'
         id: nx-version
         run: |
-          NX_VERSION= ${{ needs.dependabot-check.outputs.new-version }} || { echo "Failed to get nx version" >&2; exit 1; }
+          NX_VERSION= ${{ needs.dependabot-check.outputs.dependency-versions }} || { echo "Failed to get nx version" >&2; exit 1; }
           echo "nx-version=$NX_VERSION" >> $GITHUB_OUTPUT
       - name: 'Set nx version in package.json'
         run: |
