ci(dependabot): steps for nx migrate

diff --git a/.github/workflows/pull_request_dependabot.yml b/.github/workflows/pull_request_dependabot.yml
--- a/.github/workflows/pull_request_dependabot.yml
+++ b/.github/workflows/pull_request_dependabot.yml
@@ -39,32 +39,47 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.ref }}
-      - name: 'Run Nx Migrate if package is NX/NX-Dotnet'
+      - name: 'Run npm install'
         run: |
           npm i
+        working-directory: ${{ github.workspace }}
+      - name: Set user to github actions
+        run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
-          nx_version=$(npm show @nx/workspace version)
-          jq --arg version "$nx_version" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json || echo "Failed to update package.json version" >&2
+      - name: 'get nx version'
+        id: nx-version
+        run: |
+          NX_VERSION=$(npm show @nrwl/workspace version)
+          echo "::set-output name=nx-version::$NX_VERSION"
+      - name: 'Set nx version in package.json'
+        run: |
+          jq --arg version "$nx_version" '.version = ${{ steps.nx-version.outputs.nx-version}}' package.json > tmp.$$.json && mv tmp.$$.json package.json || echo "Failed to update package.json version" >&2
+      - name: 'Run nx migrate and create commits'
+        run: |
           npx nx migrate latest
           npx nx migrate --run-migrations --create-commits
           npx nx migrate @nx-dotnet/core
           npx nx migrate --run-migrations --create-commits
+      - name: running rest of commits
+        run: |
           git add .
+      - name: 'Check if there are changes'
+        id: check-changes
+        run: |
           # Fetch the main branch
           git fetch origin main
           # Check for differences between the current branch and the main branch
-          if git diff --quiet HEAD origin/main; then
-            echo "No changes to commit"
-          else
-            git commit -m "chore(nx): Migration items"
-            # Set up the remote tracking branch
-            git branch --set-upstream-to=origin/${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.head.ref }}
-            # Force push the changes
-            git push origin ${{ github.event.pull_request.head.ref }} --force
-          fi
-        working-directory: ${{ github.workspace }}
-
+          git diff --exit-code origin/main
+        continue-on-error: true
+      - name: 'Commit changes'
+        if: ${{ steps.check-changes.outputs.exit_code != 0 }}
+        run: |
+          git commit -m "chore: nx migrate"
+      - name: 'Push changes'
+        if: ${{ steps.check-changes.outputs.exit_code != 0 }}
+        run: |
+          git push origin ${{ github.event.pull_request.head.ref }}
   auto-merge-and-review:
     name: 'Enable Auto-Merge'
     runs-on: ubuntu-latest
